import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const fontSans = FontSans({ subsets: ["latin"], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Admin B-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased bg-green-50 w-screen h-screen", fontSans.className)}>
        <div>
          <Toaster richColors />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
